# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

image: wiktorguz/qt6

before_script:
  - apt-get update
  - apt-get install -y cmake
  - apt-get install -y doxygen
compile:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
doc:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cd doc
    - make
    - test -f ../../doc/html/index.html && echo 'index.html exists!'
